engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/PercentLiteralDelimiters:
        enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
