AllCops:
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Lint/SafeNavigationChain:
    Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Next:
  Enabled: false
