module RockerDocker
  module Templates
    ROOT_TEMPLATES = %W[#{DOCKER_COMPOSE_FILE_NAME} #{DOCKERIGNORE_FILE_NAME}].freeze

    RAILS_TEMPLATES = %w[Dockerfile entry-point.sh secrets.yml].freeze
    MYSQL_TEMPLATES = %W[Dockerfile #{SQL_DIRECTORY_NAME}/initdb-mysql.sql].freeze
    POSTGRES_TEMPLATES = %w[Dockerfile].freeze

    ROOT_DIRECTORIES = %W[#{CONFIG_DIRECTORY_NAME}].freeze
    RAILS_DIRECTORIES = %W[#{CONFIG_DIRECTORY_NAME}/#{RAILS_DIRECTORY_NAME}].freeze
    MYSQL_DIRECTORIES = %W[
      #{CONFIG_DIRECTORY_NAME}/#{MYSQL_DIRECTORY_NAME}
      #{CONFIG_DIRECTORY_NAME}/#{MYSQL_DIRECTORY_NAME}/#{SQL_DIRECTORY_NAME}
      #{CONFIG_DIRECTORY_NAME}/#{MYSQL_DIRECTORY_NAME}/#{DATA_DIRECTORY_NAME}
    ].freeze
    POSTGRES_DIRECTORIES = %W[
      #{CONFIG_DIRECTORY_NAME}/#{POSTGRESQL_DIRECTORY_NAME}
      #{CONFIG_DIRECTORY_NAME}/#{POSTGRESQL_DIRECTORY_NAME}/#{SQL_DIRECTORY_NAME}
      #{CONFIG_DIRECTORY_NAME}/#{POSTGRESQL_DIRECTORY_NAME}/#{DATA_DIRECTORY_NAME}
    ].freeze
  end
end
